### ISSUE TITLE
DSi Binary Missing? 

### ISSUE THREAD

**Issue by robinksuo** [MechanicalDragon0687/NDSForwarder#1]
I tried opening Pokemon White and fire emblem new mystery of the emblem (Japanese version) and it says I don't have DSi Binary, this detects a pirated copy being played and triggers the anti piracy measurement..

**Comment by MechanicalDragon0687** [comment]
This is not an issue with the forwarder app but an issue with nds-bootstrap not loading AP patches. TWLMenu normally copies the ap patch info to a file to allow nds-bootstrap to load it at boot. This isnt done with forwarders and so the nds files must be ap patched manually.
