### ISSUE TITLE
Custom banners not working?

### ISSUE THREAD

**Issue by Lufvave** [MechanicalDragon0687/NDSForwarder#14]
Hello, I can't get custom banners working, I created custom banners with [3DS Banner Maker](https://github.com/AlbertoSONIC/3DS_Banner_Maker) and [bannertool](https://github.com/Steveice10/bannertool), and I tried putting the created and renamed banner.bin into the rom folder and the banners folder, but it just doesn't work for me, am I doing something wrong?

**Comment by MechanicalDragon0687** [comment]
You have confused 3ds banners and dsi banners.

Forwarders are dsiware and use dsi banners. You can use tools such as MessAnimDSIco to create them or use the new 4bit bmp feature i added in the latest pre-release.

**Comment by Lufvave** [comment]
> You have confused 3ds banners and dsi banners.
> 
> Forwarders are dsiware and use dsi banners. You can use tools such as MessAnimDSIco to create them or use the new 4bit bmp feature i added in the latest pre-release.

Hello, sorry to bother again, I've tried messing around with it a lot, but any banners created by the java or .exe version of MessAnimDSIco don't work either

**Comment by MechanicalDragon0687** [comment]
You have not provided enough information to determine "why" it doesnt work or "what" is happening when you try.

Having just tested it, i can assure you that it does work. HMU on discord if you are struggling with the tool. MechanicalDragon#0687
