### ISSUE TITLE
.SRL extension support for NDS roms

### ISSUE THREAD

**Issue by y0lopix** [MechanicalDragon0687/NDSForwarder#18]
SRL files should be displayed in the forwarder generator file browser in addition to NDS files.

**Comment by MechanicalDragon0687** [comment]
.srl are dsiware. DSiWare dont get forwarded as the 3ds supports them natively. You can literally just install these either via godmode9 or by building them into a dsiware bin and using data management.

**Comment by y0lopix** [comment]
Regular DS roms extracted from Wii U Virtual Console are SRL files too.
As a workaround, I renamed them to .nds and they work properly with NDSForwarder.

**Comment by MechanicalDragon0687** [comment]
Fair enough, will do. Thanks

**Comment by lifehackerhansol** [comment]
You can potentially add a check to see if a certain binary is DSiWare: check for the DSi extended header. Then you can either warn the user or halt the operation with an error.

See https://github.com/lifehackerhansol/NDSForwarder-DSi/commit/e2551866433e62a8dd98e05b303e87bce7f180ec
