### ISSUE TITLE
Linking a game didn't work, now crashes system settings

### ISSUE THREAD

**Issue by SuperBoyne** [MechanicalDragon0687/NDSForwarder#19]
I'm on an old 2DS, running Luma, and a bunch of other stuff from the 3ds.hacks.guide tutorial on hacking a 2DS

I was trying to forward a dumped New Super Mario Bros. copy. Everything was fine, until I unwrapped the game. The photo looked like an old TV static with color, and the name was a bunch of unrecognized characters (solid ? blocks) and random characters. It didn't launch. I thought, "Oh well, I'll just remove it." Usually I delete titles through the settings and Data Management section, so I went there. I click on DSiWare, and guess what? My 2DS crashes! "Exception type: data abort". I can send a picture of the error and the error log (they call it a dump) file if you want, but I won't right now because it's too much work if it's not needed.
Anyway, how can I access my system settings? Is there a different way to delete the title/forwarder?

**Comment by MechanicalDragon0687** [comment]
Fbi > titles > scroll to the bottom > delete the corrupted looking one

This is a result of #17

**Comment by SuperBoyne** [comment]
That worked, thanks!

**Comment by MechanicalDragon0687** [comment]
If you have a chance, and use discord, please contact me there. I would like to see what part of the app failed when reading your game specifically.  MechanicalDragon#0687

**Comment by SuperBoyne** [comment]
I'd be happy to. I've sent a friend request on Discord. I'm DedFishy.
