### ISSUE TITLE
Install Failed - Pokemon Black/ White 1 and 2

### ISSUE THREAD

**Issue by Sykonik** [MechanicalDragon0687/ndsForwarder#24]
The older version of the ndsForwarder installed nds roms flawlessly such as Pokemon Black/White 1 and 2. Now with the newer version, I get an install failed (4294967295). Trying to figure out the problem without any luck

**Comment by MechanicalDragon0687** [comment]
This is pretty much always due to corrupted roms. Check the log and verify you arent getting any issues with the banners/crcs. A CRC is a checksum value that verifies that the rom is not corrupted. if the CRC is bad/wrong, then the rom is corrupted in some way

**Comment by MechanicalDragon0687** [comment]
if its a bad CRC, please dump your rom from your cartridge using the newest application (godmode9 or godmode9i) as there were some issues with dumping them on previous versions

**Comment by Sykonik** [comment]
I see, it states the the error was due to an "Invalid Banner CRC 2". The rom itself still works fine when booting with TwilightMenu++, what would you recommend to fix the banner?

**Comment by MechanicalDragon0687** [comment]
if the banner crc2 is invalid, redump the rom. If it is still invalid, hmu on discord @MechanicalDragon#0687 and we can look at the banner to see what is going on (in case its an application issue)
