### ISSUE TITLE
Install Failed: 4294967295

### ISSUE THREAD

**Issue by tyleto** [MechanicalDragon0687/ndsForwarder#26]
Using an English patched ROM, here's what the log says.

info: [Builder]looking for banner at /roms/nds/Fire Emblem - New Mystery of the Emblem.bin
info: [Builder]looking for banner at sdmc:/3ds/forwarder/banners/Fire Emblem - New Mystery of the Emblem.bin
info: [Builder]looking for custom bmp icon at sdmc:/3ds/forwarder/icons/Fire Emblem - New Mystery of the Emblem.bmp
error: [Builder]Invalid banner CRC 2
error: [Builder]Failed to create forwarder.

Any leads on how I can fix?

Edit: Forgot to mention that I can boot the rom fine using Twilight Menu++, so I don't think the issue is with that

**Comment by MechanicalDragon0687** [comment]
reinstall from 1.4.2.1

**Comment by tyleto** [comment]
As in delete all the forwarder files and move them back in? I've just done that and tried again, but instead of giving me the string of numbers its now just telling me "Install failed, check the log for errors", in which its still giving me

info: [Config]Found sdcard.fwd on romfs
info: [Config]Checking SD for templates
info: [Config]deduplicating
info: [Builder]sdcard not found. Using built in template.
info: [Builder]sdcard not found. Using built in template.
info: [Builder]looking for banner at /roms/nds/Fire Emblem - New Mystery of the Emblem.bin
info: [Builder]looking for banner at sdmc:/3ds/forwarder/banners/Fire Emblem - New Mystery of the Emblem.bin
info: [Builder]looking for custom bmp icon at sdmc:/3ds/forwarder/icons/Fire Emblem - New Mystery of the Emblem.bmp
error: [Builder]Invalid banner CRC 2
error: [Builder]Failed to create forwarder.

**Comment by MechanicalDragon0687** [comment]
I meant to replace ndsforwarder.3dsx with the 1.4.2.1 one. if you are on discord, DM me MechanicalDragon#0687

**Comment by tyleto** [comment]
Will do, big thanks!

**Comment by MechanicalDragon0687** [comment]
Romhack was poorly made and did not follow the rules for the banner (assuming it would never be loaded on a dsi/3ds)

a custom banner resolved the issue in this case.
