### ISSUE TITLE
Failing to apply a custom banner to Chrono Trigger

### ISSUE THREAD

**Issue by Yrouel** [MechanicalDragon0687/ndsForwarder#29]
I'm trying to apply a custom banner to "3351 - Chrono Trigger (Europe) (En,Fr).nds" and I simply can't get it to appear.
I created the banner with bannertool and tested it already recompiling Universal Updater which then showed my banner (the sound was borked but that's another matter).
I also recompiled latest ndsForwarder with the DEBUG options.

To clarify, the forwarder is created and the game launches/works correctly...besides not having the custom banner.

Attached both my banner and the log

[log.txt](https://github.com/MechanicalDragon0687/ndsForwarder/files/8240198/log.txt)

[3351 - Chrono Trigger (Europe) (En,Fr).zip](https://github.com/MechanicalDragon0687/ndsForwarder/files/8240199/3351.-.Chrono.Trigger.Europe.En.Fr.zip)

**Comment by MechanicalDragon0687** [comment]
Bannertool creates 3ds banners not dsiware banners. This app supports dsiware banners.
