### ISSUE TITLE
Can I add this to universal updater please?

### ISSUE THREAD

**Issue by WohaoGast2** [MechanicalDragon0687/ndsForwarder#32]
This is too useful not to be in universal updater.

**Comment by MechanicalDragon0687** [comment]
It already is

**Comment by WohaoGast2** [comment]
Oh I didn't see it ok then
I didn't know

**Comment by WohaoGast2** [comment]
I guess it's just cuz I'm bad with it like I just found out you can use the circle pad instead of needing the d-pad which, why did nintendo call the d-pad the control-pad on the 3ds? This was the only console they did that with!(Sorry for incosistent capitalizing my 3ds is in front of my keyboard and holding up my palm because I'm linking it with 3dslink to try my hand at a 3ds homebrew app)

**Comment by WohaoGast2** [comment]
Just checked, It's not there.
Unless it's a part of the forwarder pack which I can't get to work

**Comment by MechanicalDragon0687** [comment]
Look for my pfp

**Comment by WohaoGast2** [comment]
Oh it's in there ok
