### ISSUE TITLE
Playing Games in Widescreen?

### ISSUE THREAD

**Issue by Joenator** [MechanicalDragon0687/ndsForwarder#35]
Forgive me if this has been written somewhere and I didn't see it, but is there a way to make widescreen work? In the newer updates, it says widescreen is supported, but I cannot get widescreen to happen on any titles. Did I miss a post somewhere where it says what I have to do to play in widescreen?

Apologies if I missed it, and thanks in advance.

**Comment by cjunisl** [comment]
you need to use TWL Patcher

**Comment by DFelten** [comment]
There is a problem with widescreen for me. With TwilightMenu++ widescreen is working. But when run the game via forwarder it's not in widescreen. I'm using the latest version of the forwarder and the menu.

**Comment by jamzam-nds** [comment]
I am also unable to use windscreen, I've tried it with Pokemon black, white, white 2, and soul silver. The Y menu says the widescreen is on but its not :/

**Comment by MechanicalDragon0687** [comment]
which files do you have:

sd:/_nds/TWiLightMenu/extras/widescreen.pck
sd:/_nds/nds-bootstrap/wideCheatData.bin
sd:/_nds/ntr-forwarder/Widescreen.cxi
sd:/_nds/TWiLightMenu/TwlBg/Widescreen.cxi
sd:/luma/sysmodules/TwlBg.cxi

Additionally, are you enabling forced widescreen?

**Comment by jamzam-nds** [comment]
I have 
sd:/_nds/nds-bootstrap/wideCheatData.bin
sd:/_nds/ntr-forwarder/widescreen.cxi
and
sd:/_nds/ntr-forwarder/widescreen.pck
I don't have a TwiLightMenu folder in _nds, I only use ads forwarder not twilight menu++ if that's relevant

And I've tried forced widescreen and found that it will actually stretch the image, but then condense it back to the ds ratio size. So everything looks like skinnier if that makes sense

**Comment by MechanicalDragon0687** [comment]
Assuming your godmode9 is up to date (if not, see the 3ds.hacks.guide page):

open godmode9
open SDCARD and go to where your nds file is
click on the Pokemon black nds file and calculate the sha1
write down the value it gives

press B until you are back at the main godmode9 screen
put your purchased Pokemon black cartridge in the console
open GAMECART and click the nds (not trim) file there
choose calculate sha1

both values should match. if not, redump the game. if so, post the sha1 value here

**Comment by jamzam-nds** [comment]
holy shit thanks man! working now! love the software btw!!
I had to go to Luma
