### ISSUE TITLE
Cannot install 2 custom rom forwarders at same time

### ISSUE THREAD

**Issue by worsel99** [MechanicalDragon0687/ndsForwarder#36]
I have 2 hacked roms (Pokemon Blaze Black 2 and Fire Emblem 12 English for reference) that I am trying to install forwarders for. I can create a working forwarder for each individually using a custom banner for each or forcing install and using the default banner.

However, one always seems to overwrite the other - when I successfully install the first forwarder, it appears on the homescreen without issue, but when I successfully install the second, it replaces the first. It does not seem to matter what order I do these in. Additionally, I have about 20+ other forwarders installed with no issues, it seems to specifically be a problem with these two. I also have at least one other hacked rom forwarder installed (Pokemon Renegade Platinum) with no issues, it is just these two roms with problems.

Here is the [log file](https://github.com/MechanicalDragon0687/ndsForwarder/files/9741400/log.txt), this includes me creating all the other forwarders, and then various attempts at creating the two forwarders in question. Note that I removed the custom banners after a few tries to see if they were causing the problem.

**Comment by MechanicalDragon0687** [comment]
This is likely because they use the same title id.  Are you using the random TID option to ensure they generate unique title ids?

**Comment by MechanicalDragon0687** [comment]
Random tid also seems bugged in the prerelease so there is that too...

**Comment by worsel99** [comment]
I believe I tried with the random TID option as well and had the same result, I'll try again this evening after work.

**Comment by MechanicalDragon0687** [comment]
be sure that they are overwriting in data management as well, and that you do not have 40+ dsiware

**Comment by worsel99** [comment]
Just tried again with random TID and force install, same result. I also checked in FBI and confirmed that only the most recent install is showing, and I have 21 DSiWare installed. Here's another [log](https://github.com/MechanicalDragon0687/ndsForwarder/files/9743533/log.txt) showing just this attempt.

**Comment by MechanicalDragon0687** [comment]
Yeah, I am going to have to fix random tid to resolve this, probably.

**Comment by MechanicalDragon0687** [comment]
fixed by eb8882f
