### ISSUE TITLE
Allow setting custom banners for a title

### ISSUE THREAD

**Issue by spellboundtriangle** [MechanicalDragon0687/ndsForwarder#38]
Support for custom banners/icons in TWiLight Menu++ was added kinda (not really probably) recently. You can use it to set custom icons or entire banners for games without ever modifying the ROM.

It would be nice if this were carried over to ndsForwarder, perhaps with a prompt.

**Comment by MechanicalDragon0687** [comment]
It has already been possible for several versions now

**Comment by spellboundtriangle** [comment]
> It has already been possible for several versions now

It has? 🤔 Guess I missed it somehow, I'll look again. My bad,

**Comment by MechanicalDragon0687** [comment]
Assuming you mean just using custom banners/icons, yes.
Assuming you mean reading those from a custom location, no
