### ISSUE TITLE
Random TID is broken

### ISSUE THREAD

**Issue by Asia81** [MechanicalDragon0687/ndsForwarder#39]
Hello, I noticed Random TID doesn't seems to work (at least in version 1.4.4, 1.4.3 and 1.4.2.1, but it seems to work in 1.2.0-beta).
This cause to not randomize (some ?) the TIDs. In my case I have 2 romhacks (Blaze Black 2 and Volt White 2), when I install 1 it keep overwriting the other one, so I can't install both at same time.

**Comment by MechanicalDragon0687** [comment]
Yeah, i am aware of this...
Thank you for reporting this. It actually should be broken in 1.2.0 beta (maybe i fixed it?) as well. The hangup i had was that citra stubbs the required methods out meaning i need a working 3ds to test...which is currently still packed away. I'll leave this as a reminder for when i get my stuff settled.

Ps. big fan of your contributions to the community. excited to see you on my github issue tracker.

**Comment by Asia81** [comment]
I noticed some extra things about that. The Random TID generate a new TID at offset 390C, but not at 2C20 and 2F50, it mean these still the original TID.

**Comment by MechanicalDragon0687** [comment]
ah, that likely has to do with the extended header check i was doing wrong and hopefully fixed in 6e7cbc47d5587858177582391016ee67f419c0a5

**Comment by MechanicalDragon0687** [comment]
fixed by eb8882f
