### ISSUE TITLE
'Start Failed. Error 1'

### ISSUE THREAD

**Issue by TotallyNotJ** [MechanicalDragon0687/NDSForwarder#4]
according to the error screen, the file 'sdcard.nds' is not in the folder.
however, anytime i open the folder it tells me where it should be the file is there.
any help or guidance would be appreciated.

im trying to load it on an older 3ds xl.

**Comment by MechanicalDragon0687** [comment]
Is this error when opening the 3dsx, selecting the game nds file, or launching the games icon from home menu?

**Comment by TotallyNotJ** [comment]
launching from the home menu

**Comment by MechanicalDragon0687** [comment]
Then this app worked fine. Sounds like your SD is either formatted incorrectly or you didn't extract the files to the right place. Universal updater should do this for you if you installed the package from there. I suggest requesting help from the Nintendo homebrew discord.
