### ISSUE TITLE
pokemon black freezing when saving

### ISSUE THREAD

**Issue by WyattTheOtter** [MechanicalDragon0687/ndsForwarder#43]
sometimes when i try to save my game in Pokemon Black, it just freezes and doesn't save, but the background music continues to play. i've had this problem on both ndsforwarder and Twilight Menu, i have the game running on DS mode, and i have widescreen enabled

**Comment by MechanicalDragon0687** [comment]
If the problem occurs on both TWLMenu and forwarders, it is unlikely to be the app that generates the forwarders (this one).  I would normally suggest opening an issue on the nds-bootstrap tracker as that is the common thing between forwarders and twlmenu.  

That said, nds-bootstrap just updated today to fix some issues with saving in that game specifically so i would suggest looking out for a new update, then once it updates i would suggest downloading the NDS Forwarder Pack (red icon) in universal updater.
