### ISSUE TITLE
don't blacklist sd:/_nds

### ISSUE THREAD

**Issue by AlbertoDiazC** [MechanicalDragon0687/ndsForwarder#45]
I'd like to create forwarders to some emulators included into twilightmenu++, but the _nds path isn't displayed. 
If the goal is avoiding forwarding to the very nds-bootstrap files, these could be blacklisted instead.

**Comment by MechanicalDragon0687** [comment]
the intent is to prevent utilization of the system folder. the system folder wont be whitelisted/allowed. 

If those apps support forwarding, you can still manually create forwards using a pc for those or you can copy them out of the folder they are in (no guarantee they will work in that case)
