### ISSUE TITLE
error when installing a pokemon white 2 randomizer

### ISSUE THREAD

**Issue by princesselizath** [MechanicalDragon0687/ndsForwarder#46]
when I tried to installed a pokemon white 2 randomizer I made I got an error code of 0x10104 and in the log it said invalid banner CRC 3. Anyone know how to fix this

**Comment by MechanicalDragon0687** [comment]
This is due to the randomizer not properly handling banner crcs. you should be able to use the "force" option in the latest release to bypass the crc 3 check

**Comment by MechanicalDragon0687** [comment]
see https://github.com/MechanicalDragon0687/ndsForwarder/issues/41
