### ISSUE TITLE
NitroTracker Black screen

### ISSUE THREAD

**Issue by combjellly** [MechanicalDragon0687/ndsForwarder#47]
After forwarded cia is made and installed. It's launched from the home menu. The Nitrotracker logo shows up. Touch screen doesn't work. When face button is clicked, it fades to black

Homebrew seems to have a hard time defaulting to ram disk usage when accessed through ndsForwarder?

Same issue happened on twloader ++ when "run mode" is set to default and not ds.

**Comment by MechanicalDragon0687** [comment]
you should be able to set twl or nds mode by holding Y when starting the forwarder and setting the per-game settings

**Comment by MechanicalDragon0687** [comment]
closed since there has been no response.

**Comment by combjellly** [comment]
Sorry, this fix DID indeed work. Thank you for the follow up.
