### ISSUE TITLE
Forwarder doesn't work for rom hack even with force install checked 

### ISSUE THREAD

**Issue by Schweiger-Jacob** [MechanicalDragon0687/ndsForwarder#54]
The rom hack runs through twilight menu but even with the checkbox checked nds forwarder won't install it. The error code is 0x10102. The log file output was

error: [Builder]Invalid banner CRC 1
error: [Builder]Failed to create forwarder.
info: [Builder]sdcard not found. Using built in template.
info: [Builder]sdcard not found. Using built in template.
info: [Builder]looking for banner at /3ds/Platinum VCG/Platinum VGC.bin
info: [Builder]looking for banner at sdmc:/3ds/forwarder/banners/Platinum VGC.bin
info: [Builder]looking for custom bmp icon at sdmc:/3ds/forwarder/icons/Platinum VGC.bmp
error: [Builder]Invalid banner CRC 1
error: [Builder]Failed to create forwarder.

for each attempt.

**Comment by MechanicalDragon0687** [comment]
The romhack modified the icon but didn't properly recalculate the hash. Provide a valid banner or fix the file

**Comment by Schweiger-Jacob** [comment]
should force install let it install anyways?

**Comment by MechanicalDragon0687** [comment]
No. The force option falls back to the default v1 banner which should exist and be valid for all roms and romhacks. If all banners are corrupt, it does not install as that can cause home menu crashes among other things. Romhack tools have the technology to recalculate and fix the banner during modification.
